### ISSUE TITLE
Week 4 ready

### ISSUE THREAD

**Issue by JoeDowling2020** [JoeDowling2020/Independent-Project-2021#2]
@pawaitemadisoncollege week 4 is complete

**Comment by JoeDowling2020** [comment]
Key learning points: Putting these new ideas into practice definitely helps me get a better grasp of them.

Challenges: I had some weird issues with InteliJ's file associations which tied me up for a few hours today. (Thank goodness for the restore default settings buttons!!)

I could not get the insert test to pass but will try again tomorrow and if I still can't get it I might drop by for office hours!

Resources were really plentiful and useful this week! Did not have to stray too far from the course website.

**Comment by pawaitemadisoncollege** [comment]
Good to see that you've implemented hibernate in your indie project! That will set you up well to begin adding those first user stories!

- [ ] Yes! You definitely need to be able to insert a record!  If you haven't solved this yet, please share any error messages/stack traces produced when the test fails. 
- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this https://github.com/JoeDowling2020/Independent-Project-2021/blob/2fe33c8aac7a73c6f1b3f314c7ae1b85c6bb2606/src/test/Java/persistence/UserDaoTest.java#L46
- [ ] Remember to update that timeLog.md :)
